const { escapeHtml } = require("./emailUtils");

function librasTemplate({ nome, atendente, data, horario, meetUrl }) {
    const value = Object.fromEntries(Object.entries({ nome, atendente, data, horario, meetUrl }).map(([k, v]) => [k, escapeHtml(v)]));
    const text = `Olá, ${nome}!\n\nRecebemos uma solicitação de atendimento especializado em Libras.\nQuem realizará seu atendimento será ${atendente}.\n\nSeu atendimento será realizado pelo Google Meet no dia ${data}, às ${horario}.\nPedimos que esteja disponível no horário agendado. Será permitido um atraso de, no máximo, 10 minutos.\n\nAcessar chamada: ${meetUrl}`;
    const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Atendimento em Libras</title></head>
<body style="margin:0;background:#eef0f5;padding:24px 10px"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="520" style="width:100%;max-width:520px;background:#fff;border:4px solid #5b91f5;border-radius:42px;font-family:Arial,sans-serif;color:#333"><tr><td align="center" style="padding:42px 34px 18px"><img src="cid:logo-ludos" alt="Ludos" width="105" style="display:block;max-width:100%;height:auto"></td></tr><tr><td style="padding:12px 56px 0;font-size:17px;line-height:1.4">Olá, ${value.nome}!</td></tr><tr><td style="padding:20px 56px 0;font-size:17px;line-height:1.4">Recebemos uma solicitação de atendimento especializado em Libras.<br>Quem realizará seu atendimento será <strong>${value.atendente}</strong>.</td></tr><tr><td style="padding:36px 56px 0;font-size:17px;line-height:1.4">Seu atendimento será realizado pelo Google Meet, no dia <strong>${value.data}</strong>, às <strong>${value.horario}</strong>.<br>Pedimos que esteja disponível no horário agendado. Será permitido um atraso de, no máximo, 10 minutos.</td></tr><tr><td align="center" style="padding:38px 30px 22px"><a href="${value.meetUrl}" target="_blank" style="display:block;max-width:295px;background:#ffd873;color:#292929;text-decoration:none;border-radius:28px;padding:16px 20px;font-weight:bold">Acessar chamada</a></td></tr><tr><td style="padding:14px 56px 48px;font-size:15px;line-height:1.4;word-break:break-all"><a href="${value.meetUrl}" style="color:#333">${value.meetUrl}</a></td></tr></table></td></tr></table></body></html>`;
    return { html, text };
}

module.exports = { librasTemplate };
